
version: '3.6'

networks:
  radius-wifi:
    driver: bridge

services:
  db:
    image: postgres
    networks:
      - radius-wifi
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=radius
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Root_1421
    expose:
      - 5432
  webapp:
    image: mesake94/radshift:latest
    build: ./webapp
    networks:
      - radius-wifi
    volumes:
      - static:/static
      - media:/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    
  radius:
    image: mesake94/freeradius:latest
    build: ./radius-server
    networks:
      - radius-wifi
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
      - "18120:18120/tcp"
    depends_on:
      - webapp
      - db
    restart: always

volumes:
  static:
  media:
  dbdata: