# Generated by Django 3.0.14 on 2022-11-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=30)),
                ('plan_type', models.CharField(choices=[('Daily', 'Daily'), ('One-Time', 'One-Time')], default='One-Time', max_length=30)),
                ('qouta', models.PositiveIntegerField()),
                ('expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
