# Generated by Django 3.0.14 on 2022-11-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplans',
            name='expiry',
        ),
        migrations.AlterField(
            model_name='subscriptionplans',
            name='plan_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
