# Generated by Django 3.0.14 on 2022-11-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20221103_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
