# Generated by Django 3.0.14 on 2022-11-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_subscriptionplans_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
