# Generated by Django 3.0.14 on 2022-11-03 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.DJANGO_FREERADIUS_RADIUSCHECK_MODEL),
        ('client', '0004_subscriptionplans_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('rad_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.DJANGO_FREERADIUS_RADIUSCHECK_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.SubscriptionPlans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
