# Generated by Django 3.0.14 on 2022-11-15 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_usersubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='rad_check',
        ),
    ]
