# Generated by Django 3.0.14 on 2022-11-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_usersubscription_rad_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='is_active',
        ),
    ]
