# Generated by Django 3.0.14 on 2022-11-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20221128_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
