# Generated by Django 3.0.14 on 2022-11-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_usersubscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
