# Generated by Django 3.0.14 on 2022-11-29 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_usersubscription_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 29, 3, 18, 3, 817141, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
