# Generated by Django 3.0.14 on 2022-11-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_loginvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginvoucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
